### ISSUE TITLE
TIFF files

### ISSUE THREAD

**Issue by itwars** [cometeme/compress-office#1]
Hi,

Thank you for the wonderful tool. Anyway, here is a needed enhancement: handle TIFF files. It seems to be an Office for Macos issue: when we copy/paste a picture in a MS file, the picture is paste as an uncompressed TIFF file, so it add extra size to the MS file (pptx,docs,...). I've find a bunch of repo dealing with that by turning TIFF files to JPG file, and update xml files.

- https://github.com/scholer/pptx-downsizer
- https://github.com/slhck/compress-pptx

I'll like to update your code for a PR but, don't know Python... Sorry!
BR

**Comment by cometeme** [comment]
**Thanks for your nice feature request.**

Converting TIFF to JPEG is a good idea which can save lots of space, but this might cause some problems:

1. JPEG is **lossy** and it’s hard to choose a proper quality for all images.
2. JPEG **cannot contain alpha channel**, which needs to convert to solid color, this step might make images overlap in presentation files.
3. After converting we need to update `xml.rel` files, this step is dangerous and **may corrupt the document**. pptx-downsizer and compress-pptx use a simple string replace to update rel files which can work in general situation, but may run into problem when image name contains special symbols or other documents (which also contain images) embedded.

In terms of 1 and 2, I prefer converting TIFF to PNG instead of JPEG, PNG is lossless, can contain alpha channel, and more efficient than TIFF.

But updating rel file is still a problem and I need to test many different cases to make sure it’s safe to do so.

I may add this in the future, at this moment, you can use other tool (like pptx-downsizer) first to convert TIFF images, then use this tool to compress them.

**Comment by cometeme** [comment]
By the way, the problem "pasting pictures in MS Office on MacOS become TIFF" seems to have been resolved in newer versions. I pasted a screenshot in word and it shows that it's PNG format. You can check this with:

**Comment by cometeme** [comment]
By the way, the issue "pasting pictures in MS Office on MacOS become TIFF" seems to have been resolved in newer versions. I pasted a screenshot in word and it is PNG format. You can check this with `unzip -l <file>` command：

```
❯ unzip -l Doc1.docx
Archive:  Doc1.docx
  Length      Date    Time    Name
---------  ---------- -----   ----
... (other files)
   172638  01-01-1980 00:00   word/media/image1.png
...
---------                     -------
   228828                     13 files
```

I tested it on MacOS 12.1 and MS Word 16.57.

**Comment by itwars** [comment]
Thanks for your answer! That's correct, I only have TIFF in my "old" files.
